// Code generated by protoc-gen-go. DO NOT EDIT.
package proto

// Minimal proto-like structures for testing (no actual protobuf dependency)
type messageState struct{}
type sizeCache int32
type unknownFields []byte

// User represents a user in the system
type User struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email   string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Address *Address `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"` // Non-optional nested message
	Age     int32    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
}

// Address represents a user's address
type Address struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	Street  string `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City    string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Country string `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
}

// GetUserResponse is the response message for GetUser RPC
type GetUserResponse struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	User *User `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"` // Non-optional
}

// ListUsersResponse is the response message for ListUsers RPC
type ListUsersResponse struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	Users []*User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"` // Repeated field
	Total int32   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

// GetUserRequest is the request message for GetUser RPC
type GetUserRequest struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

// ListUsersRequest is the request message for ListUsers RPC
type ListUsersRequest struct {
	state         messageState
	sizeCache     sizeCache
	unknownFields unknownFields

	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
}
